#!/bin/sh

## Prints CPU and GPU temperature

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- Middle click to open htop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

gputemp=$(nvidia-settings -q gpucoretemp -t | head -n 1)
gpu=$(printf "GPU: $gputemp°C")

cpu=$(sensors | awk '/Core 1:/ {print "﨏 CPU: " $3 | "sed 's/\+//'"}')

echo $cpu $gpu
