#!/bin/bash

## Select and lauch games with dmenu

# Add games here with the path to executable
declare -A games
games[Starsector]=~/Games/starsector/starsector.sh
games[Oh-my-git]=~/Games/oh-my-git-linux/oh-my-git


choice=$(printf '%s\n' ${!games[@]} | sort | dmenu -i -l 20 -p "Select a game to play:")

[ $choice != "" ] && cd $(dirname ${games[$choice]}) && ${games[$choice]}
